// Fase 3 / módulo 6: recálculo determinista de posiciones, goleadores y fair play.
import "server-only";
import { prisma } from "@/lib/prisma";

export async function recalcularTorneo(torneoId: string) {
  const [teams, matches] = await Promise.all([prisma.equipo.findMany({ where: { torneoId }, select: { id: true } }), prisma.partido.findMany({ where: { jornada: { torneoId }, estado: "FINALIZADO" }, include: { acta: { include: { goles: true, tarjetas: { include: { jugador: { select: { equipoId: true } } } } } } } })]);
  const table = new Map(teams.map((team) => [team.id, { jugados: 0, ganados: 0, empatados: 0, perdidos: 0, golesFavor: 0, golesContra: 0, puntos: 0, puntosFairPlay: 0 }]));
  const players = new Map<string, { goles: number; amarillas: number; rojas: number }>();
  for (const match of matches) { if (!match.acta) continue; const local = table.get(match.equipoLocalId)!; const visitor = table.get(match.equipoVisitanteId)!; const localGoals = match.acta.goles.filter((g) => g.equipoId === match.equipoLocalId).length; const visitorGoals = match.acta.goles.filter((g) => g.equipoId === match.equipoVisitanteId).length; local.jugados++; visitor.jugados++; local.golesFavor += localGoals; local.golesContra += visitorGoals; visitor.golesFavor += visitorGoals; visitor.golesContra += localGoals; if (localGoals > visitorGoals) { local.ganados++; local.puntos += 3; visitor.perdidos++; } else if (visitorGoals > localGoals) { visitor.ganados++; visitor.puntos += 3; local.perdidos++; } else { local.empatados++; visitor.empatados++; local.puntos++; visitor.puntos++; } for (const goal of match.acta.goles) { const stat = players.get(goal.jugadorId) ?? { goles: 0, amarillas: 0, rojas: 0 }; if (!goal.autogol) stat.goles++; players.set(goal.jugadorId, stat); } for (const card of match.acta.tarjetas) { const stat = players.get(card.jugadorId) ?? { goles: 0, amarillas: 0, rojas: 0 }; if (card.tipo === "AMARILLA") stat.amarillas++; else stat.rojas++; players.set(card.jugadorId, stat); const team = table.get(card.jugador.equipoId); if (team) team.puntosFairPlay += card.tipo === "AMARILLA" ? 1 : 3; } }
  await prisma.$transaction([prisma.clasificacionEquipo.deleteMany({ where: { torneoId } }), prisma.estadisticaJugador.deleteMany({ where: { torneoId } }), ...[...table].map(([equipoId, data]) => prisma.clasificacionEquipo.create({ data: { torneoId, equipoId, ...data } })), ...[...players].map(([jugadorId, data]) => prisma.estadisticaJugador.create({ data: { torneoId, jugadorId, ...data } }))]);
}
