-- Fase 3 / módulos 5, 6 y 7: actas, disciplina y estadísticas.
CREATE TYPE "TipoTarjeta" AS ENUM ('AMARILLA','ROJA'); CREATE TYPE "EstadoSancion" AS ENUM ('ACTIVA','CUMPLIDA','REVOCADA');
CREATE TABLE "Acta" ("id" TEXT PRIMARY KEY,"partidoId" TEXT NOT NULL,"observaciones" TEXT,"finalizadaAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Alineacion" ("id" TEXT PRIMARY KEY,"actaId" TEXT NOT NULL,"jugadorId" TEXT NOT NULL,"titular" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "Gol" ("id" TEXT PRIMARY KEY,"actaId" TEXT NOT NULL,"jugadorId" TEXT NOT NULL,"equipoId" TEXT NOT NULL,"minuto" INTEGER NOT NULL,"autogol" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Tarjeta" ("id" TEXT PRIMARY KEY,"actaId" TEXT NOT NULL,"jugadorId" TEXT NOT NULL,"tipo" "TipoTarjeta" NOT NULL,"minuto" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Sancion" ("id" TEXT PRIMARY KEY,"jugadorId" TEXT NOT NULL,"torneoId" TEXT NOT NULL,"motivo" TEXT NOT NULL,"jornadaInicioNumero" INTEGER NOT NULL,"duracionFechas" INTEGER,"indefinida" BOOLEAN NOT NULL DEFAULT false,"estado" "EstadoSancion" NOT NULL DEFAULT 'ACTIVA',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ClasificacionEquipo" ("id" TEXT PRIMARY KEY,"torneoId" TEXT NOT NULL,"equipoId" TEXT NOT NULL,"jugados" INTEGER NOT NULL DEFAULT 0,"ganados" INTEGER NOT NULL DEFAULT 0,"empatados" INTEGER NOT NULL DEFAULT 0,"perdidos" INTEGER NOT NULL DEFAULT 0,"golesFavor" INTEGER NOT NULL DEFAULT 0,"golesContra" INTEGER NOT NULL DEFAULT 0,"puntos" INTEGER NOT NULL DEFAULT 0,"puntosFairPlay" INTEGER NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "EstadisticaJugador" ("id" TEXT PRIMARY KEY,"torneoId" TEXT NOT NULL,"jugadorId" TEXT NOT NULL,"goles" INTEGER NOT NULL DEFAULT 0,"amarillas" INTEGER NOT NULL DEFAULT 0,"rojas" INTEGER NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "Acta_partidoId_key" ON "Acta"("partidoId"); CREATE UNIQUE INDEX "Alineacion_actaId_jugadorId_key" ON "Alineacion"("actaId","jugadorId"); CREATE INDEX "Sancion_jugadorId_torneoId_estado_idx" ON "Sancion"("jugadorId","torneoId","estado"); CREATE UNIQUE INDEX "ClasificacionEquipo_torneoId_equipoId_key" ON "ClasificacionEquipo"("torneoId","equipoId"); CREATE UNIQUE INDEX "EstadisticaJugador_torneoId_jugadorId_key" ON "EstadisticaJugador"("torneoId","jugadorId");
ALTER TABLE "Acta" ADD FOREIGN KEY ("partidoId") REFERENCES "Partido"("id") ON DELETE CASCADE; ALTER TABLE "Alineacion" ADD FOREIGN KEY ("actaId") REFERENCES "Acta"("id") ON DELETE CASCADE; ALTER TABLE "Alineacion" ADD FOREIGN KEY ("jugadorId") REFERENCES "Jugador"("id") ON DELETE RESTRICT; ALTER TABLE "Gol" ADD FOREIGN KEY ("actaId") REFERENCES "Acta"("id") ON DELETE CASCADE; ALTER TABLE "Gol" ADD FOREIGN KEY ("jugadorId") REFERENCES "Jugador"("id") ON DELETE RESTRICT; ALTER TABLE "Gol" ADD FOREIGN KEY ("equipoId") REFERENCES "Equipo"("id") ON DELETE RESTRICT; ALTER TABLE "Tarjeta" ADD FOREIGN KEY ("actaId") REFERENCES "Acta"("id") ON DELETE CASCADE; ALTER TABLE "Tarjeta" ADD FOREIGN KEY ("jugadorId") REFERENCES "Jugador"("id") ON DELETE RESTRICT; ALTER TABLE "Sancion" ADD FOREIGN KEY ("jugadorId") REFERENCES "Jugador"("id") ON DELETE RESTRICT; ALTER TABLE "Sancion" ADD FOREIGN KEY ("torneoId") REFERENCES "Torneo"("id") ON DELETE CASCADE; ALTER TABLE "ClasificacionEquipo" ADD FOREIGN KEY ("torneoId") REFERENCES "Torneo"("id") ON DELETE CASCADE; ALTER TABLE "ClasificacionEquipo" ADD FOREIGN KEY ("equipoId") REFERENCES "Equipo"("id") ON DELETE CASCADE; ALTER TABLE "EstadisticaJugador" ADD FOREIGN KEY ("torneoId") REFERENCES "Torneo"("id") ON DELETE CASCADE; ALTER TABLE "EstadisticaJugador" ADD FOREIGN KEY ("jugadorId") REFERENCES "Jugador"("id") ON DELETE CASCADE;
